var firstname = "Aritra";
var lastname = "Barua";
console.log(firstname);
console.log(lastname);
var fullname = firstname.concat(lastname);
console.log(fullname);
var one = "1";
var two = "2";
console.log(one);
console.log(two);
var twelve = one.concat(two);
console.log(twelve);